### PR TITLE
Change executable path in makefile

### LINKED ISSUE #11: Update Makefile to reflect the change in executable path
After pull request #4 was merged, the path to the entry files changed from `cmd` to `cmd/bloggen`. However, the `Makefile` in root directory is still pointing the `cmd/*.go` when it should now be `cmd/bloggen/*.go` since all  files where moved down the tree to  the newly created directory  `bloggen`.

Also, the `run` and `preview` rules in makefile which use the `cmd/markdown` path should also be updated to `cmd/bloggen/markdown` path.

Thank you

### PR DESCRIPTION
**Pull request by Antoineio**
:wave: 

Just a little PR for fixing the issue #11 
In this PR i updated the `Makefile` with the new paths. 
And i tested it (in this [comment](https://github.com/emanuelquerty/bloggen/issues/11#issuecomment-2115125151)) and it's works  :)

### CODE REVIEW

**Comment by emanuelquerty** [comment]
@Antoineio  Apologies for the delay to review the pull requests.

I changed the PR's titles because that's what I meant in the [contributions guidelines](https://github.com/emanuelquerty/bloggen/blob/main/CONTRIBUTING.md). But reading it myself again, it does seem confusing and infers what you understood. So apologies for the confusion. I will update the guidelines to make it more clear. But what I meant is that the title should just tell in short what the pull request is like `Fix help command` and then in the description, you can refer to the issue as `This pull requests fixes #3` for example or you could refer it in any way, like how you did for both of your pull requests as in `Just a little PR for fixing the issue #11`. That's perfectly fine ☺️ 

I changed both of PR's title to reflect what I meant and I will update the guidelines shortly.

**Comment by emanuelquerty** [comment]
@Antoineio But as far as this pull request is concerned, I reviewed it and it solves the issue. I will approve it and merge it. 

Thank you ☺️

**Review by emanuelquerty — APPROVED** [review]
This PR successfully fixes the issue. Looks great!

**Comment by Antoineio** [comment]
@emanuelquerty No worries, for the delay. 
Sorry, i think i misunderstood
I'm glad to know that everything is working properly. :tada: 
Thank you for the details in your message, i understood better now :pray:

**Pull request merged**
